# ONLINE RETAIL SMALL E COM CHECKDATA2

In [ ]:
import pandas as pd
df=pd.read_excel("C:/-----SEM4-----/projects/data eng/Online Retail.xlsx")

In [ ]:
df.to_csv("C:/-----SEM4-----/projects/data eng/Online Retail.csv",index='False')
#since excel files takes a lot of time to load i have converted it to csv files and later we will start looking at the dataset

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [20]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [21]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [32]:
#now first let us check are there any null values in every column
print("no of null values in INVOICE NO:" , df["InvoiceNo"].isnull().sum())
print("no of null values in INVOICE Date:", df["InvoiceDate"].isnull().sum())
print("no of null values in Stockcode: " , df["StockCode"].isnull().sum())
print("no of null values in Description: " , df["Description"].isnull().sum())
print("no of null values in Quantity: " , df["Quantity"].isnull().sum())
print("no of null values in Unitprice: " , df["UnitPrice"].isnull().sum())
print("no of null values in Customer ID: " , df["CustomerID"].isnull().sum())
print("no of null values in Country: " , df["Country"].isnull().sum())

no of null values in INVOICE NO: 0
no of null values in INVOICE Date: 0
no of null values in Stockcode:  0
no of null values in Description:  1454
no of null values in Quantity:  0
no of null values in Unitprice:  0
no of null values in Customer ID:  135080
no of null values in Country:  0

ok when we checked as u can see there are (1454/541909) ~ 0.26% .null values in description and
(1,35,000 /5,41,909) ~ 24.9% null values in customer id

since 0.26 percent is very low might have we would drop it completely

In [ ]:
dfcl_null = df
dfcl_null=dfcl_null[(dfcl_null["Description"]==0) & (dfcl_null["CustomerID"]== 0 )]
dfcl_null.shape
dfcl_null.head
#hence i might as well drop those null values

<bound method NDFrame.head of Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []>

In [ ]:
dfcl=df
dfcl["Description"]=dfcl["Description"].fillna("no description")
print("previous rows before null:",df.shape)
print("after rows after dropping null:",dfcl.shape)
print("description null:",dfcl['Description'].isnull().sum())
dfcl=dfcl.dropna(subset=["CustomerID"])
print("customer id null:", dfcl["CustomerID"].isnull().sum())

previous rows before null: (541909, 8)
after rows after dropping null: (541909, 8)
description null: 0
customer id null: 0

-now we have  cleared the null values by filling description with no description and dropping null values of customer id
 cus if customer id is null there is no point of storing it cus with out it how do we know wether the customer is legit or not it is bad case
 2. now lets check duplicate values

In [60]:
print("no of duplicate values in INVOICE NO:" , dfcl["InvoiceNo"].duplicated().sum())
print("no of duplicate values in INVOICE Date:", dfcl["InvoiceDate"].duplicated().sum())
print("no of duplicate values in Stockcode: " , dfcl["StockCode"].duplicated().sum())
#print("no of duplicate values in Description: " , dfcl["Description"].duplicated.sum())
print("no of duplicate values in Quantity: " , dfcl["Quantity"].duplicated().sum())
print("no of duplicate values in Unitprice: " , dfcl["UnitPrice"].duplicated().sum())
print("no of duplicate values in Customer ID: " , dfcl["CustomerID"].duplicated().sum())
print("no of duplicate values in Country: " , dfcl["Country"].duplicated().sum())

no of duplicate values in INVOICE NO: 384639
no of duplicate values in INVOICE Date: 386369
no of duplicate values in Stockcode:  403145
no of duplicate values in Quantity:  406393
no of duplicate values in Unitprice:  406209
no of duplicate values in Customer ID:  402457
no of duplicate values in Country:  406792

In [71]:
print(dfcl["CustomerID"].unique().shape)
#as previously we saw duplicate value of customerid as 402457 but here there are only 4372 unique id that indicates these id people
#have been  regular customers or have been ordering more from the same online retail store
print(dfcl["InvoiceNo"].unique())

(4372,)
[536365 536366 536367 ... 581585 581586 581587]

In [77]:
#now as gpt said check wether rows are duplicated
print("exact rows duplicated are:",dfcl.duplicated().sum())
duplicates = dfcl[dfcl.duplicated(keep=False)]
duplicates.sort_values(["InvoiceNo", "StockCode", "InvoiceDate"]
).head(30)

exact rows duplicated are: 5225

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom

In [79]:
same_product = dfcl[
    (dfcl["InvoiceNo"] == 536409) &
    (dfcl["StockCode"] == 21866)
]

print(same_product)
dfcl[dfcl["InvoiceNo"] == 536409]

    InvoiceNo StockCode                  Description  Quantity  \
494    536409     21866  UNION JACK FLAG LUGGAGE TAG         1
517    536409     21866  UNION JACK FLAG LUGGAGE TAG         1

            InvoiceDate  UnitPrice  CustomerID         Country
494 2010-12-01 11:45:00       1.25     17908.0  United Kingdom
517 2010-12-01 11:45:00       1.25     17908.0  United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
483,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,3,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
484,536409,21479,WHITE SKULL HOT WATER BOTTLE,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
486,536409,22785,SQUARECUSHION COVER PINK UNION FLAG,1,2010-12-01 11:45:00,6.75,17908.0,United Kingdom
487,536409,22975,SPACEBOY CHILDRENS EGG CUP,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
488,536409,22972,CHILDREN'S SPACEBOY MUG,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
490,536409,22568,FELTCRAFT CUSHION OWL,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
491,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
492,536409,22664,TOY TIDY DOLLY GIRL DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
493,536409,21609,SET 12 LAVENDER BOTANICAL T-LIGHTS,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
495,536409,20669,RED HEART LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
496,536409,90129F,RED GLASS TASSLE BAG CHARM,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
497,536409,90210B,CLEAR ACRYLIC FACETED BANGLE,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
498,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,1,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
499,536409,21955,DOORMAT UNION JACK GUNS AND ROSES,1,2010-12-01 11:45:00,7.95,17908.0,United Kingdom
500,536409,72802C,VANILLA SCENT CANDLE JEWELLED BOX,1,2010-12-01 11:45:00,4.25,17908.0,United Kingdom
501,536409,22109,FULL ENGLISH BREAKFAST PLATE,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
502,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,5,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
503,536409,22531,MAGIC DRAWING SLATE CIRCUS PARADE,1,2010-12-01 11:45:00,0.42,17908.0,United Kingdom
504,536409,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
505,536409,22183,CAKE STAND VICTORIAN FILIGREE MED,1,2010-12-01 11:45:00,6.75,17908.0,United Kingdom
506,536409,21678,PAISLEY PATTERN STICKERS,6,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
507,536409,21676,FLOWERS STICKERS,6,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
508,536409,84625A,PINK NEW BAROQUECANDLESTICK CANDLE,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
509,536409,84625C,BLUE NEW BAROQUE CANDLESTICK CANDLE,3,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
510,536409,21931,JUMBO STORAGE BAG SUKI,2,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
511,536409,85169B,BLACK LOVE BIRD CANDLE,12,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
512,536409,16238,PARTY TIME PENCIL ERASERS,28,2010-12-01 11:45:00,0.21,17908.0,United Kingdom
513,536409,20668,DISCO BALL CHRISTMAS DECORATION,24,2010-12-01 11:45:00,0.12,17908.0,United Kingdom
514,536409,84906,PINK B'FLY C/COVER W BOBBLES,1,2010-12-01 11:45:00,5.95,17908.0,United Kingdom
515,536409,21867,PINK UNION JACK LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
516,536409,22075,6 RIBBONS ELEGANT CHRISTMAS,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
518,536409,21326,AGED GLASS SILVER T-LIGHT HOLDER,12,2010-12-01 11:45:00,0.65,17908.0,United Kingdom
519,536409,21065,BOOM BOX SPEAKER GIRLS,1,2010-12-01 11:45:00,5.95,17908.0,United Kingdom
520,536409,22074,6 RIBBONS SHIMMERING PINKS,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
522,536409,20713,JUMBO BAG OWLS,1,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
523,536409,20966,SANDWICH BATH SPONGE,2,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
524,536409,21116,OWL DOORSTOP,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
525,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,2,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
526,536409,22633,HAND WARMER UNION JACK,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
528,536409,22198,LARGE POPCORN HOLDER,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
529,536409,21824,PAINTED METAL STAR WITH HOLLY BELLS,3,2010-12-01 11:45:00,1.45,17908.0,United Kingdom
530,536409,21823,PAINTED METAL HEART WITH HOLLY BELL,3,2010-12-01 11:45:00,1.45,17908.0,United Kingdom
531,536409,22153,ANGEL DECORATION STARS ON DRESS,6,2010-12-01 11:45:00,0.42,17908.0,United Kingdom
532,536409,22197,SMALL POPCORN HOLDER,2,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
533,536409,85099B,JUMBO BAG RED RETROSPOT,2,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
534,536409,85099F,JUMBO BAG STRAWBERRY,1,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
535,536409,20717,STRAWBERRY SHOPPER BAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
536,536409,20723,STRAWBERRY CHARLOTTE BAG,1,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
538,536409,21980,PACK OF 12 RED RETROSPOT TISSUES,12,2010-12-01 11:45:00,0.29,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
540,536409,22112,CHOCOLATE HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom

Exact duplicate rows were identified. However, identical records may represent repeated quantities of the same product within a single invoice rather than erroneous duplication. Since the dataset does not provide a unique transaction-line identifier, these records cannot confidently be classified as data-entry duplicates. Therefore, they were retained to avoid potentially underestimating sales quantity and revenue.